name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
  issues: read
  packages: write
jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Install Node.js 21 # Must be after corepack is enabled.
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn run lint:all
      - name: Format
        run: yarn run format:check
      - name: Build TypeScript
        run: yarn run tsc
      - name: Build
        run: yarn workspaces foreach -A run build:all
      - name: Build Storybook
        run: yarn workspace @radapp.io/rad-components run build-storybook
      - name: Run Tests
        run: yarn run test:all
      - name: Run E2E Tests
        run: yarn run test:e2e
  build-and-publish-container:
    name: Build and Publish Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Install Node.js 21 # Must be after corepack is enabled.
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build TypeScript
        run: yarn run tsc
      - name: Build Image
        run: yarn build:backend --config ../../app-config.yaml --config ../../app-config.dashboard.yaml
      - name: Build Image
        run: yarn build-image
      - name: Analyze Image
        uses: ./.github/actions/analyze-image
        with:
          image: ghcr.io/radius-project/dashboard:latest
      - name: Push Image (to ghcr.io on push to main)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: docker push ghcr.io/radius-project/dashboard:latest
