name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
  issues: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Install Node.js 20 # Must be after corepack is enabled.
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn run lint:all
      - name: Format
        run: yarn run format:check
      - name: Build
        run: yarn workspaces foreach -A run build:all
      - name: Build Storybook
        run: yarn workspace rad-components run build-storybook
      - name: Run Tests
        run: yarn run test:all
      - name: Run E2E Tests
        run: yarn run test:e2e
